SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `account_stake_holders`;
DROP TABLE IF EXISTS `cu_activity_sectors`;
DROP TABLE IF EXISTS `cu_addresses`;
DROP TABLE IF EXISTS `cu_business_links`;
DROP TABLE IF EXISTS `cu_cities`;
DROP TABLE IF EXISTS `cu_civil_states`;
DROP TABLE IF EXISTS `cu_countries`;
DROP TABLE IF EXISTS `cu_customer_documents`;
DROP TABLE IF EXISTS `cu_customer_photos`;
DROP TABLE IF EXISTS `cu_customers`;
DROP TABLE IF EXISTS `cu_district`;
DROP TABLE IF EXISTS `cu_documents_type`;
DROP TABLE IF EXISTS `cu_individuals`;
DROP TABLE IF EXISTS `cu_marital_status`;
DROP TABLE IF EXISTS `cu_member_categories`;
DROP TABLE IF EXISTS `cu_members`;
DROP TABLE IF EXISTS `cu_membership_status`;
DROP TABLE IF EXISTS `cu_membership_status_changes`;
DROP TABLE IF EXISTS `cu_memberships`;
DROP TABLE IF EXISTS `cu_moral_documents`;
DROP TABLE IF EXISTS `cu_moral_signatories`;
DROP TABLE IF EXISTS `cu_morals`;
DROP TABLE IF EXISTS `cu_sex`;
DROP TABLE IF EXISTS `cu_stake_holder_types`;
DROP TABLE IF EXISTS `member_types`;
SET FOREIGN_KEY_CHECKS = 1;
